version: '2'

services:
  bind:
    image: ubuntu:latest
    restart: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - .data/bind:/data


version: '2'

services:
  bind:
    image: debian:latest
    restart: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - .data/bind:/data

version: '2'
services:
  bind:
    build: ./bind
    restart: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    tty: true
    
    volumes:
    - .data/bind:/data

FROM debian:latest

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y bind9
COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh
ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["/usr/sbin/named"]

COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh
ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["/bin/bash"]




CMD ["/usr/sbin/named"]


nsupdate_create_template = '''\
server {0}
update add {1} {2} A {3}
send\
'''
nsupdate_create_ptr = '''\
update add {0} {1} PTR {2}
send\
'''
nsupdate_delete_template = '''\
server {0}
update delete {1} A
send
update delete {1} PTR
send\
'''